Functional model for serial to socket data transfer from Basilisk
oresat/oresat-simulator pull request #2
Opened 2024-09-24 20:56 UTC by ThePakkrat

Socket to serial works for transferring Basilisk output to anything with a USB port.

This has been tested via loopback on one computer.

sock_ser_official is where everything is housed

sock_ser_terminal_model is a functional test program that transfers a user input via the same method.

Use GTKterm to test outputs if you want to verify what is being sent.

2024-09-28 06:54 UTC, ThirteenFish requested changes
A lot of this looks like Basilisk examples so I won't comment on the content of those, only the parts it looks like we've modified.

2024-09-28 06:54 UTC, ThirteenFish commented on .gitignore
> +
Ignoring files for a single project that aren't universal to your development process and aren't automatically generated by the project should be added to `.git/info/exclude` instead of the top level `.gitignore`. This way you don't step on anyone else's toes who want to develop on your project.

The three locations to ignore things in git:
- `~/.gitignore`: for things universal to your personal development process, like vim's `.swp` files.
- `.git/info/exclude`: For your personal development local to this project, like todo files or venvs
- `.gitignore`: For things generated by the project that shouldn't be committed, like python's `__pycache__` and `.pyc` files.

2024-09-28 06:54 UTC, ThirteenFish commented on README.md
This is nicely formatted for a regular text file but Github will try to render it as a markdown file (specifically [Github Flavored Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)) and when it's displayed [on the repo page](https://github.com/oresat/oresat-simulator/tree/socket_shenanigans), where most people will read it, it comes out all mangled.

To have it look good when rendered it should be touched up, paying attention in particular to:
- [Headings](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#headings), things which aren't the top level should consider H2 or H3 headers.
- [Paragraphs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#paragraphs) and [line breaks](https://github.github.com/gfm/#hard-line-break).
- [Lists](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#lists).
- [Code highlighting](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code), both inline and block.
- [Links](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#links).

This goes for the other two READMEs as well.

2024-09-28 06:54 UTC, ThirteenFish commented on README.md
> +You will need to install pyserial within the virtual environment that you run Basilisk in.
It might be helpful to mention specifically installing Basilisk in a Python virtual environment is the preferred method.
> Start by installing Basilisk in a Python virtual environment.

This has the added benefit of being unambiguous about the kind of virtual environment being used.

2024-09-28 06:54 UTC, ThirteenFish commented on README.md
> +sudo usermod -a -G dialout [root_username]
Installing `pyserial` with `apt` explicitly won't install it in the virtual environment. This is a workaround for being able to run server with `sudo`, but if the permissions are set appropriately then you won't have to. Either mention that the `apt` install is a fallback for not being able to set permissions or just remove it.

Additionally, this project has a `pyproject.toml` which maintains the list of pip dependencies. Instead of having the user install each dependency by hand they can be instructed to `pip install .` and that will grab everything out of `pyproject.toml`.

Also `root_username` can just be `username` as you want to give yourself the `dialout` group, not root, which doesn't care.

2024-09-28 06:54 UTC, ThirteenFish commented on sock_ser_official/parse_tle.py
While it's a fun exercise, we shouldn't be writing our own TLE parser. [PyEphem](https://rhodesmill.org/pyephem/quick.html), specifically `ephem.readtle()`, is an existing library that we already use in other projects for this.

2024-09-28 06:54 UTC, ThirteenFish commented on sock_ser_official/client.py
Usually outdated code should just be deleted (it lives on in git history) but this may be a useful foundation for the start of an automated test suite. You could move this to a new top level directory called `tests` (the standard location) and keep this around for a simple known-good client for testing `server.py`

2024-09-28 06:54 UTC, ThirteenFish commented on sock_ser_official/server.py
Not for this pull request, but maybe in the next one: consider using [argparse](https://docs.python.org/3/library/argparse.html) to let the user configure the port and the serial device. I already had a `/dev/ttyUSB0` and I wanted to run this on `/dev/ttyUSB1`.

2024-09-28 06:54 UTC, ThirteenFish commented on sock_ser_official/magDataOresat0-aug20.txt
What is this file for? As far as I can tell it's not consumed by anything.

2024-09-28 06:54 UTC, ThirteenFish commented on sock_ser_official/scenarioMagneticFieldWMM.py
> +            while True:
`run()` seems to return the same collection of vectors every time so it doesn't really make sense to run it in a loop (this becomes especially apparent if you try to use the graphical display). In the future it may make more sense to have Basilisk generate data until we say stop but for now it doesn't.

Fitting the code to the problem, this should probably run once and stop.

2024-09-28 06:54 UTC, ThirteenFish commented on sock_ser_official/scenarioMagneticFieldWMM.py
> +                    )
The `if` here is being used to alter `True` and `False`, but the condition (`yesno.upper() == 'Y'`) already evaluates to `True` or `False`. The `if` can be elided then:
```python
data = run(
    yesno.upper() == 'Y',
    'elliptical',
)
```

2024-09-28 06:54 UTC, ThirteenFish commented on sock_ser_official/scenarioMagneticFieldWMM.py
> +if __name__ == "__main__":
You've been copying around the client code a bunch now, it may be worth considering how to turn it into a python module. It is out of scope for this PR but possibly for the next one, ponder how I as a user would use your client code. I'd want to `import something` and then give my data to that `something` I imported and have it figure out how to send it over the network for me.

2024-09-28 06:54 UTC, ThirteenFish commented on sock_ser_official/scenarioMagneticFieldWMM.py
> +    yesno = input("Do you want a graphical display or not? Y/n: ")
This is another great candidate for using `argparse` (again outside the scope of this PR, but maybe in the next one). If I want to run this script many times I'd like to just have a single command line argument to turn this setting on or off instead of having to re-answer the question every time.

2024-09-28 06:54 UTC, ThirteenFish commented on sock_ser_official/scenarioMagneticFieldWMM.py
> +    return to_send
This is doing array indexing again, and with python's various iteration methods there's usually a better tool. In this case we can use a generator comprehension (similar to the list comprehensions from before), unpacking (the `*`), and `bytes.join()` to put everything back together:
```python
def pack_array_data(array):
    return b''.join(struct.pack('3f', *vec) for vec in array)
```

2024-09-28 06:54 UTC, ThirteenFish commented on sock_ser_official/scenarioMagneticFieldWMM.py
> +    return mG_vals
Numpy arrays are smart, they know how to do many things, among them scalar multiplication. This function can become:
```python
def T_to_mG(data):
    # convert each value to mG. 1Tesla = 10^7 mG
    return data * 10**7
```

The `format()` statement here has no effect, it returns a string which is immediately discarded. I'm also skeptical of what the `round()` is doing here but we probably don't want to arbitrarily chop off precision? If it is necessary, the `round()` method of the numpy array can be used: `return (data * 10**7).round(4)`.

`pack_array_data` down below is flexible enough that it can accept a numpy array directly without change.

2024-10-08 22:29 UTC, ThePakkrat commented on .gitignore
> +
This makes a lot of sense.

2024-10-08 22:33 UTC, ThePakkrat commented on README.md
> +sudo usermod -a -G dialout [root_username]
I think my toml file is pretty sparse but this makes sense.

2024-10-08 22:34 UTC, ThePakkrat commented on sock_ser_official/parse_tle.py
Note for the future when going back in - albeit TLEs I didn't work on.

2024-10-08 22:36 UTC, ThePakkrat commented on sock_ser_official/server.py
I had this feature in an earlier version so it would be pretty easy to re-implement.

2024-10-08 22:36 UTC, ThePakkrat commented on sock_ser_official/magDataOresat0-aug20.txt
Good question.

2024-10-08 22:40 UTC, ThePakkrat commented on sock_ser_official/scenarioMagneticFieldWMM.py
> +if __name__ == "__main__":
I agree.

2024-10-08 22:59 UTC, ThirteenFish approved these changes

2024-10-08 23:00 UTC, merged